trigger:
- master

pool:
  name: "Pool"

variables:
  - group: bonner-deploy
  - name: RepositoryName
    value: mosca-docker

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '10.x'
            displayName: 'Install Node.js'

          - task: DockerInstaller@0
            displayName: Setup Docker

          - pwsh: docker build -t $(RepositoryName) .
            displayName: Build

          - task: ECRPushImage@1
            inputs:
              awsCredentials: 'AWS'
              regionName: $(RegistryLocation)
              imageSource: 'imagename'
              sourceImageName: $(RepositoryName)
              repositoryName: $(RepositoryName)