trigger:
- master

pool:
  name: "Pool"

resources:
 repositories:
   - repository: bonner-deploy
     type: github
     name: moritonal/bonner-deploy

stages:
  - template: templates\build_and_release.yml@bonner-deploy
    parameters:
      ContainerRegistryName: mosca-docker
      DockerComposeName: mosca