trigger:
- master

pool:
  name: "Pool"

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'bonner-registry'
    repository: 'mosca-docker'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest